### ISSUE TITLE
Decision Importance

### ISSUE THREAD

**Issue by m-gurung11** [Logic-Legends/Decision-Making-Frmwk#19]
As a user I want to specify how important the decision is so I can understand how it affects the type of voting method I should choose

**ACCEPTANCE CRITERA**

**Scenario 1 - Content**
GIVEN I am using the Decision Making Framework
WHEN I am on the Decision Importance screen
THEN I should see the title text 'Importance'
AND I should see the question text below it as 'How important is the decision?'

**Scenario 2 - Responses**
GIVEN I am using the Decision Making Framework
WHEN I am on the Decision Importance screen
THEN I should see 2 radio buttons below the question text
AND I should the options as 'Low' and 'High'

**Scenario 3 - Info tooltip**
GIVEN I am on the Decision Importance screen
WHEN I hover on the info icon
THEN I should see a tooltip
AND I should see the text 'Importance = the significance and/or value of the decision at hand"
AND a close (X) icon on the top right

**Scenario 3a - Close tooltip**
GIVEN the info pop-up is open
WHEN I tap on close
THEN the tooltip should disappear

**Scenario 5 - Continue**
GIVEN I am on the Decision Importance screen
WHEN I have selected a response
AND I click Continue
THEN I should be directed to the Decision Capacity screen

**Scenario 6 - Back**
GIVEN I am on the Decision Importance screen
WHEN I click on the Back button
THEN I should be directed to the Decision Makers screen
AND the input I previously entered should be displayed

**Scenario 7 - Error Messaging**
GIVEN I am on the Decision Importance screen
WHEN I have not selected either option
AND I click Continue
THEN I should see an error message, 'Please select a response'

**Scenario 8 - URL**
GIVEN I am on the Decision Importance screen
WHEN I check the URL
THEN it should be https://domain/importance

**Comment by leilafaez** [comment]
For scanario 3 do we need the hover or click on info icon? if we need hover by onMouseEnter and onMouseLeave we can handle the opening and closing the tooltip so we dont need next scenario which is related to x btn for closing but if we want to handle it by onClick eventListener we can do next scenario

**Comment by m-gurung11** [comment]
Hi Leila I think its better to go with click as the experience should be mobile first and hovering with a mouse is not possible on mobile phones. I'll change the AC to click tomorrow

**Comment by leilafaez** [comment]
Is that possible , the saving data process in browser local storage for back btn be done next iteration?

**Comment by leilafaez** [comment]
for now all the acceptance creteria meets except :
1) for tooltip me and Luan use different kind of tooltip that we should decide which one should be kept. so until to make a decision for that I dont put x btn. because it works by clicking now
2)for showng previuos data on back btn I cannot finish it in this sprint so maybe it is better to be done in next iteration by making another ticket

**Comment by leilafaez** [comment]
I fix the tooltips by following step1 desing for importance page
I save the user selection on radio btn on local storage

**Comment by mhallaq** [comment]
Nice work Leila, I have noticed that sometime the form can proceed to the next step even the user did not select any option.

**Comment by leilafaez** [comment]
we use useContext hook instead of local storage. for step 1 to 6 it is a good idea for using this hook because we dont need to save them- when we use this hook by refereshing the page the data will disapear so for last step as a result page we need to save data on local storage. Also we need to think during each step if user refresh the page what they will see at the result page!

**Comment by mhallaq** [comment]
I have tested the screen different scenarios , it works fine and pass the values to the next step.
